on:
  pull_request:
    types: [reopened, opened, synchronize, edited]

name: Create S3 Environment
jobs:
  create_or_update_pr_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v

      - name: Install Dependencies
        run: npm ci

      - name: Build Site
        run: npm run build

      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "diff"
          actions_comment: true

      # - name: cdk deploy
      #   uses: youyo/aws-cdk-github-actions@v2
      #   with:
      #     cdk_subcommand: 'deploy'
      #     cdk_stack: 'stack1'
      #     cdk_args: '--require-approval never'
      #     actions_comment: false

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
