on:
  pull_request:
    types: [closed]

name: Destroy PR Env
jobs:
  destroy_pr_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/github-script@v7
        id: generate-branch-name
        with:
          script: |
            return `${{ github.head_ref }}`.toLowerCase().replace(/[^a-z0-9-]/g, '-').substring(0, 63) + "-" + `${{ github.actor }}`;
          result-encoding: string

      - name: cdk destroy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "destroy"
          cdk_stack: "${{ env.STACK_NAME }}"
          cdk_args: "--parameters BucketName=${{ env.STACK_NAME }} --require-approval never"
          actions_comment: true
        env:
          STACK_NAME: ${{ steps.generate-branch-name.outputs.result }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
