on:
  pull_request:
    types: [closed]

name: Destroy PR Env
jobs:
  destroy_pr_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: cdk destroy
      #   uses: youyo/aws-cdk-github-actions@v2
      #   with:
      #     cdk_subcommand: "destroy"
      #     cdk_stack: "*"
      #     cdk_args: "--parameters BucketName=${{ steps.generate-branch-name.outputs.result }} --require-approval never"
      #     actions_comment: false

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
