on:
  pull_request:
    types: [closed]

name: Destroy PR Env
jobs:
  destroy_pr_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install AWS CDK
        run: sudo npm install -g aws-cdk

      - name: Install Dependencies
        run: npm ci

      - uses: actions/github-script@v7
        id: generate-branch-name
        with:
          script: |
            return `${{ github.head_ref }}`.toLowerCase().replace(/[^a-z0-9-]/g, '-').substring(0, 63) + "-" + `${{ github.actor }}`;
          result-encoding: string

      - name: CDK destroy
        run: cdk destroy --context stackName=${{ steps.generate-branch-name.outputs.result }} --force

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
